### ISSUE TITLE
Remapped field data doesn't correspond to original types

### ISSUE THREAD

**Issue by DenWav** [ProjectTestificate/SrgLib#2]
```
Caused by: java.lang.IllegalArgumentException: Remapped field data (EnumChatFormat/A) doesn't correspond to original types (net/minecraft/util/text/TextFormatting/field_96303_A)
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:383)
        at net.techcable.srglib.mappings.SimpleMappings.putField(SimpleMappings.java:76)
        at net.techcable.srglib.mappings.Mappings.lambda$chain$4(Mappings.java:205)
        at net.techcable.srglib.mappings.SimpleMappings.forEachField(SimpleMappings.java:160)
        at net.techcable.srglib.mappings.Mappings.chain(Mappings.java:202)
        at com.destroystokyo.papergradle.tasks.TaskGenSpigotSrgs.doStuff(TaskGenSpigotSrgs.java:77)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:624)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:607)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 15 more
```

This is with MCP mappings `snapshot_20161119` and BuildData commit hash `77931c01e72ff84c004a310b121a72b52f0efdd5`.

**Comment by DenWav** [comment]
And the same error is thrown for `snapshot_20161124`.

**Comment by DenWav** [comment]
Here's the relevant code snippet: https://github.com/PaperMC/PaperGradle/blob/master/src/main/java/com/destroystokyo/papergradle/tasks/TaskGenSpigotSrgs.java

**Comment by DenWav** [comment]
I'm not totally convinced these checks are actually doing anything useful, so I "fixed" the issue by removing them.

https://github.com/Techcable/SrgLib/blob/master/src/main/java/net/techcable/srglib/mappings/SimpleMappings.java#L76-L81

https://github.com/Techcable/SrgLib/blob/master/src/main/java/net/techcable/srglib/mappings/SimpleMappings.java#L65-L70

**Comment by Techcable** [comment]
Turns out it was a bug in the chaining algorithm that was causing the issues
